const EXES = [
  { name: "Maria Rita", age: 17, image: "", colors: ["#df5d9c", "#6b3cba"], compatibility: 98, description: "Uma história que o algoritmo se recusou a esquecer.", reason: "Histórico amoroso detectado." },
  { name: "Clarisse Alves", age: 17, image: "assets/clarisse-1.jpeg" , colors: ["#e68c61", "#8b3b95"], compatibility: 96, description: "O passado voltou com uma nova notificação.", reason: "Memórias antigas encontradas." },
  { name: "Laura Rayssa", age: 18, image: "", colors: ["#3e9bb5", "#6d48a6"], compatibility: 94, description: "Você achou que tinha acabado. O algoritmo discorda.", reason: "Histórico relevante encontrado." }
];

const $ = s => document.querySelector(s); let current = 0, passAttempts = 0, searchingShown = false;
const passLines = ["Tem certeza?", "Você realmente acha que consegue fugir do passado?", "Ela já está no histórico. Não adianta.", "PASSAR NÃO APAGA MEMÓRIAS.", "Erro: impossível fugir das ex."];

function go(id){ document.querySelectorAll('.screen').forEach(x => x.classList.remove('active')); $('#'+id).classList.add('active'); }
function toast(message){ const t=$('#toast'); t.textContent=message; t.classList.add('visible'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>t.classList.remove('visible'),2400); }
function renderCard(){ const ex=EXES[current]; if(!ex){ go('final'); return; } $('#counter').textContent=current+1; $('#total').textContent=EXES.length; $('#progress-bar').style.width=`${((current+1)/EXES.length)*100}%`; const photo=ex.image ? `background-image:linear-gradient(transparent 38%,#180d2bd9),url('${ex.image}');background-size:cover;background-position:center` : `--c1:${ex.colors[0]};--c2:${ex.colors[1]}`;
 $('#dating-card').innerHTML=`<div class="photo" style="${photo}">${ex.image?'':'<div class="portrait"><span></span></div>'}<div class="photo-info"><h2>${ex.name}, ${ex.age}</h2><small>COMPATIBILIDADE: ${ex.compatibility}%</small></div></div><div class="card-copy"><span class="compat">MATCH ALTAMENTE SUSPEITO</span><p>${ex.description}</p><div class="reason"><strong>MOTIVO DO MATCH</strong><span>${ex.reason}</span></div></div>`;
}
function moveCard(direction,done){ const c=$('#dating-card'); c.style.transition='transform .35s ease, opacity .35s ease'; c.style.transform=`translateX(${direction*520}px) rotate(${direction*18}deg)`; c.style.opacity='0'; setTimeout(()=>{c.style.transition='';c.style.transform='';c.style.opacity='1';done();},360); }
function nextCard(){ current++; passAttempts=0; if(current<EXES.length){ renderCard(); return; } if(!searchingShown){ searchingShown=true; go('searching'); setTimeout(()=>{ $('#new-count').textContent=EXES.length; $('#more-title').innerHTML=`novos perfis<br>encontrados.`; go('more'); },1800); } else go('final'); }
function pass(){ if(passAttempts<passLines.length){ toast(passLines[passAttempts++]); return; } moveCard(-1,nextCard); }
function like(){ moveCard(1,()=>{launchConfetti();go('match');}); }
function launchConfetti(){ const canvas=$('#confetti'),ctx=canvas.getContext('2d'); canvas.width=canvas.offsetWidth*devicePixelRatio;canvas.height=canvas.offsetHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio); const bits=Array.from({length:130},()=>({x:Math.random()*canvas.offsetWidth,y:-20-Math.random()*canvas.offsetHeight*.4,vy:2+Math.random()*4,vx:-2+Math.random()*4,c:['#ff74ad','#fff0a5','#aa83ff','#fff'][Math.floor(Math.random()*4)],s:4+Math.random()*6,r:Math.random()*6})); let frame=0; (function draw(){ctx.clearRect(0,0,canvas.offsetWidth,canvas.offsetHeight);bits.forEach(b=>{b.x+=b.vx;b.y+=b.vy;b.vy+=.05;b.r+=.11;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.r);ctx.fillStyle=b.c;ctx.fillRect(-b.s/2,-b.s/2,b.s,b.s*.65);ctx.restore();});if(frame++<180)requestAnimationFrame(draw)})(); }
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go)); $('#options-btn').onclick=()=>{current=0;searchingShown=false;renderCard();go('cards')}; $('#pass-btn').onclick=pass; $('#like-btn').onclick=like; $('#show-more').onclick=()=>{current=0;renderCard();go('cards')}; $('#restart-btn').onclick=()=>{current=0;searchingShown=false;go('welcome')}; $('#accept-btn').onclick=()=>go('accepted');
let startX=0; $('#dating-card').addEventListener('pointerdown',e=>startX=e.clientX); $('#dating-card').addEventListener('pointerup',e=>{const delta=e.clientX-startX;if(Math.abs(delta)>70)delta>0?like():pass();});
$('#ex-count').textContent=EXES.length;
